# Generated by Django 6.0 on 2026-03-31 17:48

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="notice",
            name="content",
            field=tinymce.models.HTMLField(default=""),
            preserve_default=False,
        ),
    ]
