# Generated by Django 6.0 on 2026-04-01 05:08

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0002_notice_content"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="notice",
            name="content",
        ),
        migrations.AlterField(
            model_name="event",
            name="details",
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="event",
            name="event_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="event",
            name="name",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="notice",
            name="description",
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="notice",
            name="notice_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="notice",
            name="title",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
